name = "PassivBot"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["PassivBot Contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1.6"
HTTP = "1.0"
WebSockets = "1.6"
JSON3 = "1.13"
DataFrames = "1.5"
DataStructures = "0.18"
CSV = "0.10"
Optim = "1.7"
BlackBoxOptim = "0.6"
Distributions = "0.25"
StatsBase = "0.34"
Plots = "1.38"
ArgParse = "1.1"
